### ISSUE TITLE
attach is unable to set reviewer flags

### ISSUE THREAD

**Issue by jankeromnes** [mozilla/git-bz-moz#26]
When using `git bz attach -e SHA`, I can uncomment one of the following lines:

    #Review: :vingtetun
    #Review: 21@vingtetun.org
    #Review: :me+

but with no effect. I'd love to be able to request a review from `git bz attach`, or carry over a previous `r+`.

**Comment by fitzgen** [comment]
FWIW, this happens to me every now and then, but it is pretty intermittent.

**Comment by amccreight** [comment]
I don't have the bug handy, but Nathan Froyd filed a bug in bugzilla about this issue a month or so ago, and there was actually some bugzilla-side issue that was affecting bz attach.

**Comment by past** [comment]
This has also been affecting me every time I attach a patch on BMO. @amccreight do you know the bug number of the bugzilla-side issue?

**Comment by froydnj** [comment]
I was getting flat-out failures when trying to `git bz attach`; the bug is https://bugzilla.mozilla.org/show_bug.cgi?id=1150057

But that's been fixed, and I haven't seen any problems since then.

**Comment by past** [comment]
The past 2 weeks setting the reviewer has been hit-or-miss for me on Mac. On Linux it hasn't worked once.

**Comment by amccreight** [comment]
Does it give any error message? Does it work better if you use the specific email address instead of some partial match?

**Comment by past** [comment]
This is the typical message I get on Linux (where it fails regardless of whether I use the email or the IRC nick):

$ git bz attach -e -n HEAD
Got bad status line - retrying...
Attached Let-the-debugger-server-started-by-GCLI-debug-chro.patch

**Comment by past** [comment]
In bug 1173301 I set both f? and r? to an irc nick and only the f? got through.

**Comment by amccreight** [comment]
Hopefully my REST API rewrite will eliminate some of these weird failures people get setting reviewer flags.

**Comment by fitzgen** [comment]
> Hopefully my REST API rewrite will eliminate some of these weird failures people get setting reviewer flags.

FYI, WFM since I pulled the REST API changes.

**Comment by amccreight** [comment]
In hindsight, I wonder if this was because it was setting the wrong flag id for reviewer in products besides Core, or maybe the support for Firefox flags was a little flakey. Anyways, I'll close this for now.

**Comment by past** [comment]
I haven't tried in all my systems yet, but I think this worked correctly the last couple of times that I tried. Thanks!
