### ISSUE TITLE
git moves are not changed to hg renames when attaching a patch in bugzilla

### ISSUE THREAD

**Issue by Standard8** [mozilla/git-bz-moz#28]
STR:

1) Create a patch with git mv
2) Attach a patch to bugzilla

Actual Results
No hg rename/move annotations in the patch on bugzilla

Expected Results
hg rename/move annotations.

For example, see https://bug1022594.bugzilla.mozilla.org/attachment.cgi?id=8472973

When I created the patch, I did:
`git mv browser/components/loop/test/xpcshell/test_loopservice_get_loop_char_pref.js browser/components/loop/test/xpcshell/test_loopservice_loop_prefs.js`
`git mv browser/components/loop/test/mochitest/browser_mozLoop_charPref.js browser/components/loop/test/mochitest/browser_mozLoop_prefs.js`

These haven't been recorded.

**Comment by Standard8** [comment]
I can't remember what exactly we had here, but I'm fairly sure we were just missing the lines visually, so I'll close this.

**Comment by ehsan** [comment]
Perhaps you were confused by Splinter hiding the file move? :)
