### ISSUE TITLE
When editing a patch before attaching, show patch diff below

### ISSUE THREAD

**Issue by fitzgen** [mozilla/git-bz-moz#46]
It is often good to see the changes for patch #n so I have a better idea of who to ask for review/feedback and if I accidentally left a header include in that isn't used anymore etc. Good to just have a chance to review the patch right before it is attached.

**Comment by amccreight** [comment]
Do you mean editing the file attach thing, where you can set the reviewer and commit comment and so forth?  In general, I'd worry about giant patches, but I can see how it might be handy for little patches.  (FWIW, I usually just use git-show in another console, though then you have to fiddle around with seeing which patch you are actually attaching.)

**Comment by fitzgen** [comment]
> Do you mean editing the file attach thing, where you can set the reviewer and commit comment and so forth?

Yup, that's what I meant.

> In general, I'd worry about giant patches, but I can see how it might be handy for little patches.

If it's at the bottom of the buffer, why does it matter? Either way, you will only see the first n lines of the patch unless you actively inspect the diff.

> (FWIW, I usually just use git-show in another console, though then you have to fiddle around with seeing which patch you are actually attaching.)

That's what I try to do as well, but I am not perfect and so having it automatically happen means I am more likely to actually review the patch before attaching it. Especially when patch queues have multiple patches; that's when I start to review each patch less before uploading because it requires just a little more effort from me to do it manually and in practice that means it gets skipped (like all those header include nits you found in my onGarbageCollection runnable patches (still, something I should work on, but tools should help me, not the other way around)).
