### ISSUE TITLE
git bz apply doesn't understand reviewboard

### ISSUE THREAD

**Issue by dmose** [mozilla/git-bz-moz#48]
As an example, 

```
$ git bz apply 1177933
Bug 1177933 - Provide run script or mach command for eslint in mobile/android

$
```
applies neither of the two patches in the bug.  I wonder if this is related to the use of reviewboard...

**Comment by amccreight** [comment]
I didn't know this feature of git bz existed, but I am not surprised that it doesn't understand reviewboard links.

**Comment by mshal** [comment]
I've only tested this a little bit - I would appreciate some additional verification.

**Comment by amccreight** [comment]
I don't use ReviewBoard but I figured this is better than nothing. Please file new issues for whatever corner cases still don't work with the patch.

**Comment by amccreight** [comment]
Thanks for fixing this!
