### ISSUE TITLE
The commit rewriting done by `git bz file` should add "Bug NNNNNNN - " prefix

### ISSUE THREAD

**Issue by fitzgen** [mozilla/git-bz-moz#49]
Right now it links the bug url in the commit, but it should add "Bug NNNNNNN - " as a prefix to the first line, eg "Fix the foo; r=someone" should become "Bug 1234567 - Fix the foo; r=someone".

**Comment by froydnj** [comment]
Add

```
[bz]
    add-url-method = subject-prepend:Bug %d - 
```

(note the extra space at the end of that line) to your `.gitconfig` and it will do just that.

**Comment by Nephyrin** [comment]
Given that this is primarily used by Mozilla, it seems reasonable to make this the default behavior and let others fiddle with their configure for the current behavior

**Comment by amccreight** [comment]
Yeah, totally. The URL thing is pretty useless.
