### ISSUE TITLE
2-factor auth on Bugzilla breaks cookie searches

### ISSUE THREAD

**Issue by Standard8** [mozilla/git-bz-moz#51]
Currently the 2fa implementation on bugzilla has changed cookies to expire at the end of the session. This breaks git-bz-moz, as the cookies are no longer saved to the cookies.sqlite file.

This may change again, follow the dicussion in [bug 1202281](https://bugzilla.mozilla.org/show_bug.cgi?id=1202281).

However, it may be time to consider fixing issue #30 and use the API keys that are now be available.

**Comment by globau** [comment]
the issue with cookies is a bug that i'm trying to track down and will fix on bmo - ie. cookies shouldn't be expiring at the end of the session (i'm having problems reproducing the issue reliably however).

**Comment by amccreight** [comment]
I have a branch in issue #30 that works with the api key.

**Comment by amccreight** [comment]
The rewritten version that uses the API key and ditches cookie support entirely has landed a little while ago.
