### ISSUE TITLE
make attach do something smarter in the face of inconclusive matches from bugzilla

### ISSUE THREAD

**Issue by froydnj** [mozilla/git-bz-moz#52]
I tried filing a patch with a reviewer.  Unfortunately, the person's bugzilla `:` name is actually a prefix of two (!) names and so `git bz attach` fails with a `No Conclusive Match` error from bugzilla.

It would be nice if it let you resolve the ambiguity, and perhaps even remember that resolution for next time so you don't have to keep doing it.

**Comment by amccreight** [comment]
bzexport implements something like this, so hopefully we'll get that for free if we convert to their rest API stuff. I don't think it has any provision for saving disambiguation, but that's a good idea. Or just ask this particular reviewer to pick a less ambiguous IRC nick. ;)

**Comment by amccreight** [comment]
This should be fixed now. I just took advantage of bzexport's code, which will present a nice little menu to disambiguate. I think it even caches your selection.
