### ISSUE TITLE
Remove git bz push

### ISSUE THREAD

**Issue by amccreight** [mozilla/git-bz-moz#54]
This lets you update bugzilla at the same time as you do a push (I think), which doesn't seem super useful given that we have Pulsebot, so I'm inclined to remove it if there are no objections. I have found users at Mozilla for every other command, so maybe somebody uses this one.

**Comment by fitzgen** [comment]
Fwiw, I don't use it.

**Comment by amccreight** [comment]
I'm also planning to remove "bz edit --pushed" and "bz edit --fix" which are similar.
