### ISSUE TITLE
Add a way to assign the bug to yourself when attaching a patch

### ISSUE THREAD

**Issue by amccreight** [mozilla/git-bz-moz#68]
It would be convenient to be able to assign the bug to yourself when uploading a patch.

The basic feature would be adding an AssignedTo field to the file you edit for bz attach -e. There could be pre-filled in things for the current assignee, for assigning it to yourself, and for resetting it to the default.

There could also be more automatic behavior, like if there is no current assignee you assign it to yourself by default. This could still be commented out from the edit file if you don't want it, but it is the most common use case.

**Comment by fitzgen** [comment]
And perhaps automatically set the bug status to ASSIGNED rather than NEW if you do this?
