### ISSUE TITLE
git bz apply adds a bogus "Bug 1234567" to the commit message

### ISSUE THREAD

**Issue by ehsan** [mozilla/git-bz-moz#69]
See https://hg.mozilla.org/try/rev/2df1c96f43bd for example.

Note that I have the following in my ~/.gitconfig:

```
[bz]
	add-url-method = "subject-prepend:Bug %d - "
	add-url-ignore-remote-commits = true
```

cc @amccreight

**Comment by ehsan** [comment]
D'oh, nevermind, 1234567 is coming from the original patch  :)

**Comment by amccreight** [comment]
FYI, I added your add-url-method to the default configuration so you should be able to get rid of it now.

**Comment by amccreight** [comment]
A few places do check for existing bug numbers in patch names, so you could imagine something fixing this. It is probably not common enough to worry about, though. :)
