### ISSUE TITLE
adding bug #s to commits doesn't check for existing bug numbers

### ISSUE THREAD

**Issue by froydnj** [mozilla/git-bz-moz#73]
I think we did check for this prior to the great bzapi rewrite and asked the user what to do.  Now we produce commits like "Bug XXX - Bug YYY - msg", which nobody likes.

**Comment by amccreight** [comment]
What are the steps to reproduce?

**Comment by froydnj** [comment]
I did:

1. `git bz attach -e $BUG1 commit...range`
2. Realize that's not the bug I wanted to attach things to.
3. `commit..range` now has "Bug YYY - " prefixes.
4. `git bz attach -e $BUG2 commit...range`
5. Realize the commit messages now have "Bug XXX - Bug YYY - " prefixes

`bz.add-url-method` is set to `subject-prepend:Bug %d - ` in my `.gitconfig` if that makes any difference.
