### ISSUE TITLE
`add-url-ignore-remote-commits = true` should be the default

### ISSUE THREAD

**Issue by fitzgen** [mozilla/git-bz-moz#75]
Regularly takes a minute before my $EDITOR gets popped up.

I run it like this (in the most recent case, which was one of the slow ones):

```
git bz file 'Firefox/Developer Tools' -e HEAD^
```

**Comment by amccreight** [comment]
Do you have |add-url-ignore-remote-commits = true| set under [bz]? Doing that will fix one source I know of for absurd slow things. Without that, it does something ridiculous like check the entire history to see if your commit has already been committed. We should probably make that the default. So let me know if it helps.

**Comment by fitzgen** [comment]
Ok, I just set that, will report back next time I file a new bug.

**Comment by fitzgen** [comment]
Ok, it is pretty much instant now, thanks!

I agree that this should be the default.

**Comment by amccreight** [comment]
@ehsan:  you added this flag. Is there some reason you can think of that we shouldn't just enable this for everybody by default? (I'm not sure what it is even useful for but I guess we could leave the code in...)
