### ISSUE TITLE
Add testing mode that does not push to bugzilla

### ISSUE THREAD

**Issue by amccreight** [mozilla/git-bz-moz#80]
It would be nice to have a built-in way to disable any actual changes to Bugzilla, for use when testing why something is going wrong. The ideal way would be a fake server mode that would print out what is getting pushed to it, but something that just aborts before anything real happens might be okay, too. Right now, I just hack this up every time I need to debug something.

**Comment by indygreg** [comment]
We have a Docker-based BMO server in the version-control-tools repository testing environment. That's how we test bzexport and other tools interacting with Bugzilla. See e.g. https://github.com/mozilla/version-control-tools/blob/master/hgext/bzexport/tests/test-newbug.t.

**Comment by Standard8** [comment]
An alternative would be to make it easy to use one of the test bugzillas, e.g. bugzilla-dev or one of the landfill ones.

Currently we can only specify one API key globally, which makes its a pain to use other servers.
