### ISSUE TITLE
Need better error message when the reviewer doesn't accept the review requests

### ISSUE THREAD

**Issue by aethanyc** [mozilla/git-bz-moz#91]
I post a patch via `git bz attach -e` with a reviewer set, and got the following exception.
```
Traceback (most recent call last):
  File "/Users/tlin/Projects/moz-git-tools/git-bz", line 1790, in <module>
    do_attach(*args)
  File "/Users/tlin/Projects/moz-git-tools/git-bz", line 1425, in do_attach
    attach_commits(bug, commits, edit=global_options.edit)
  File "/Users/tlin/Projects/moz-git-tools/git-bz", line 1354, in attach_commits
    bug.create_patch(description, comment, filename, patch, obsoletes=obsoletes, patch_flags=patch_flags)
  File "/Users/tlin/Projects/moz-git-tools/git-bz", line 861, in create_patch
    self.server.auth.rest_request('POST', 'bug/%s/attachment' % self.id, data=o)
  File "/Users/tlin/Projects/moz-git-tools/git-bz-moz/bzauth.py", line 149, in rest_request
    method, url, j['message']))
Exception: <exception str() failed>
```

I then print the return JSON object, and got the following. 
```js
{u'code': 32000, u'message': u"David Baron :dbaron: \u231a\ufe0fUTC-5 (busy February 1-10) <dbaron@dbaron.org> is not currently accepting 'review' requests.", u'documentation': u'http://www.bugzilla.org/docs/tip/en/html/api/', u'error': True}
```

I'll be nice to have a message saying that the reviewer doesn't accept the review requests.

**Comment by amccreight** [comment]
That's odd. The code looks like it should print out something. It also looks like this code is just taken from upstream, and they haven't changed anything there. I'll figure out what is going wrong.

**Comment by amccreight** [comment]
I filed a bug upstream: https://bugzilla.mozilla.org/show_bug.cgi?id=1336147

But I'll just fix it locally, too. Thanks for the bug report.

**Comment by amccreight** [comment]
Ok, I have fixed this. It now prints out the error message:

Exception: REST error on POST to https://bugzilla.mozilla.org/rest/bug/1316755/attachment: David Baron :dbaron: ⌚️UTC-5 (busy February 1-10) <dbaron@dbaron.org> is not currently accepting 'review' requests.

**Comment by aethanyc** [comment]
@amccreight, thank you for fixing this issue promptly.
