### ISSUE TITLE
 "git bz apply" treats the virtual/hidden commit-message from MozReview as part of the patch

### ISSUE THREAD

**Issue by chenpighead** [mozilla/git-bz-moz#94]
Here's the [STR](https://bugzilla.mozilla.org/show_bug.cgi?id=1346321#c12).

It can be seen from the STR, "git bz apply" creates the "commit-message-***" file locally as part of the imported commit, and then apply the virtual file unexpectedly. This caused an [accidentally landing of extra commit-message](https://bugzilla.mozilla.org/show_bug.cgi?id=1345498#c20).

**Comment by zalun** [comment]
This is a MozReview bug as described in https://bugzilla.mozilla.org/show_bug.cgi?id=1346321#c17

**Comment by chenpighead** [comment]
Yeah, since Byron Jones has already assigned himself in [Bug 1346321](https://bugzilla.mozilla.org/show_bug.cgi?id=1346321), I think we can close this issue.

**Comment by zalun** [comment]
I think it should be reopened. It would be better to use the patch directly from HG instead of the one from MozReview.

**Comment by chenpighead** [comment]
I thought If we could prevent the virtual/hidden commit-message file from showing in the raw diff downloaded by clicking `Download Diff` on MozReview, this issue could be gone. @zalun, are you saying that [Bug 1346321](https://bugzilla.mozilla.org/show_bug.cgi?id=1346321) may not fix this issue?

**Comment by zalun** [comment]
This will fix the issue, but using this feature is not the best solution. Code is pushed to HG, then it's loaded to MozReview and analyzed there. Then diff is taken from MozReview objects and provided for download. IMO it would be best to shorten this path. @smacleod suggested HG repository should be used. In the end MozR is just a review tool, the diff should be treated as an additional way to review the code.

**Comment by chenpighead** [comment]
IMHO, git-bz-moz is a tool for interacting with Bugzilla only, so it shouldn't be his responsibility to tell whether this patch is from HG or from a fork on MozReview, as long as the patch is what exactly attached to Bugzilla. Since MozReview couldn't provide a copy of the patch on Bugzilla (for reasons like the consistency between MozReview and Bugzilla during the review process), I think at least a link to the patch is pretty reasonable.

Right now, it seems to me that the link to the patch is broken by the new virtual/hidden commit-message feature. The `view raw` links still point to the HG formatted patch without the virtual/hidden files, however, `Download Diff` points to a diff including the virtual/hidden files. I think the best way might be correcting the `Download Diff` link. After all, MozReview already has all the information it needs.

**Comment by zalun** [comment]
`Download Diff` link is fixed - no virtual files included.

**Comment by chenpighead** [comment]
@zalun thank you for fixing this. :-)
