### ISSUE TITLE
Cannot git bz apply patches in Bug 1375969

### ISSUE THREAD

**Issue by aethanyc** [mozilla/git-bz-moz#95]
I run `git bz apply 1375969`, and get the following exception. I don't know it's an issue on the tool or on the server.

```Exception: REST error on GET to https://bugzilla.mozilla.org/rest/user?names=emilio+bugs@crisal.io: There is no user named 'emilio bugs@crisal.io'. Either you mis-typed the name or that user has not yet registered for a Bugzilla account.```

**Comment by amccreight** [comment]
I'm guessing that the email has a +, but it isn't being escaped properly.
