### ISSUE TITLE
filing bugs with commits ending in "; r=build-peer" does not strip the r= info for the bug title

### ISSUE THREAD

**Issue by froydnj** [mozilla/git-bz-moz#97]
...whereas if I were to file a new bug with a commit ending in "; r=froydnj", the "; r=froydnj" would not appear in the bug title.

See, for instance, https://bugzilla.mozilla.org/show_bug.cgi?id=1413538

It's possible that I could manually edit the r= information out in this case, but it would really be much nicer if it were automatically stripped.

**Comment by amccreight** [comment]
I think the problem is that reviewPattern doesn't include -.
https://github.com/mozilla/git-bz-moz/blob/master/splitreviewer.py#L31

**Comment by amccreight** [comment]
There's no tests for semicolon, either, so adding a few of those would be good.

**Comment by amccreight** [comment]
Never mind, there is a test for ;
